title: TPaste
description: The package allows you to communicate directly with Pastebin from your Python application, either logged in or anonymously.
theme: jekyll-theme-cayman
avatar: https://raw.githubusercontent.com/jekyll/jekyll/master/docs/favicon.ico
show_downloads: true
google_analytics: UA-114697093-1
layout: default
comments: true
messenger: true

# My Custom Configs
ttl:
  seo:
    og-image: https://raw.githubusercontent.com/rytotul/rytotul.github.io/master/img/voldemort.png
